runemetrics = "RASPIA-runemetrics-request"
runescape_hiscores = "RASPIA-hiscores-request"
runescape_clans = "RASPIA-clans-request"
runescape_seasonal_events = "RASPIA-Seasonal-Events-request"
weird_gloop_GE = "RASPIA-GE-Request"
weird_gloop_VOS = "RASPIA-VOS-Request"
